#!/bin/bash

tmp=$(dirname "$0")
path=$(realpath "${tmp}/pandown")
dir=$(dirname "$path")
header="${dir}/header.yaml"
css="${dir}/style.css"
format="html"
csl="${dir}/styles/apa.csl"
args=""

while getopts ":h:i:t:f:c:C:s:-:" o; do
  case ${o} in
    i)
      input=$OPTARG
      ;;
    t)
      target=$OPTARG
      ;;
    h)
      header=$OPTARG
      ;;
    f)
      format=$OPTARG
      ;;
    s)
      csl=$OPTARG
      ;;
    c)
      css="${css} --css=${OPTARG}"
      ;;
    C)
      css=$OPTARG
      ;;
    \?)
      echo "Invalid Option: $OPTARG" 1>&2
      ;;
    :)
      echo "Invalid Option: $OPTARG requires an argument" 1>&2
      ;;
    -)
      case ${OPTARG} in
        "help"*)
          echo "pandown [OPTIONS] -i [INPUT] -t [TARGET]"
          echo "--help    -- Show this message"
          echo "-c CSS    -- Append CSS file for styling, if omited uses default"
          echo "-C CSS    -- Overwrites CSS file for styling, if omited uses default"
          echo "-f FORMAT -- Format of the input file, it's 'markdown' by
          default"
          echo "-h HEADER -- YAML file with header information, if omited uses
          default"
          echo "-s CSL    -- CSL file for citation style, if omited uses
          default"
          echo "-i INPUT  -- Input file path"
          echo "-t TARGET -- Target file path"
          exit 0
          ;;
      esac
      ;;
  esac
done
shift $((OPTIND -1))

if [ -z $target ]
then
  target=${input%\.*}.pdf
fi

if [ -z $input ]
then
  echo -e "No input defined!\nSee --help for more information"
  exit 1
fi

echo "Compiling ${input} into ${target}..."
pandoc $header $input -t $format --filter pandoc-citeproc --csl=$csl \
  --css=$css $args -s -o $target &> /dev/null
if [[ $? == 0 ]]
then
  echo "Done!"
  exit 0
fi
echo "Something went wrong!"
exit 127
